// File generated by Gemini for manual Firebase configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // main 프로젝트 (ireadschool-800f8) — android 는 google-services.json 과 맞춤
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXmLxnMc6FS6EDfTT-rWGB67M3tT9yV2E',
    appId: '1:474725837334:web:881b94bd37c2113299e337',
    messagingSenderId: '474725837334',
    projectId: 'ireadschool-800f8',
    authDomain: 'ireadschool-800f8.firebaseapp.com',
    storageBucket: 'ireadschool-800f8.firebasestorage.app',
    measurementId: 'G-9G076707L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanU6GvNiPXbVPoQfSAM0jZ0N1IfRw1fo',
    appId: '1:474725837334:android:5b787d58acb4584d99e337',
    messagingSenderId: '474725837334',
    projectId: 'ireadschool-800f8',
    storageBucket: 'ireadschool-800f8.firebasestorage.app',
  );
}
